### PR TITLE
Create Jenkinsfile

### PR DESCRIPTION
**Pull request by j-mcavoy**

### CODE REVIEW

**Comment by timothyhollabaugh** [comment]
What will this do?

**Comment by j-mcavoy** [comment]
I’m testing the CI server, it’s linked to the github organization. You have
to make one of these files in the repos you want the CI system to do stuff
with with tasks to run. This is a test one just to see that the CI will work

**Comment by timothyhollabaugh** [comment]
Should it be merged, then? Or are you just testing with it in a pull request?

**Comment by j-mcavoy** [comment]
Just testing it, it doesn’t have to be merged, you can close the request

**Pull request closed without merging**
